### ISSUE TITLE
GUI: Can't edit existing map

### ISSUE THREAD

**Issue by ocobble** [amymcgovern/pytello#5]
When you load an existing map into the GUI, you can't edit it. Clicking on any square will result in the error shown in the screenshot: "Unsupported operand types for /: int and nonetype." I will try to investigate it more when I have some time. 

![Error](https://user-images.githubusercontent.com/29961363/74683700-61ba6480-518f-11ea-9625-f4aeee4cc8fb.PNG)

**Comment by amymcgovern** [comment]
Fixed
